/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.junk.application;

import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elmer
 */
public class MainForm extends javax.swing.JFrame {
    private DecimalFormat df = new DecimalFormat("#,##0.00");
    public HashMap<String,DencFile> dataMap;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        readData();
    }
    private DefaultTableModel model = null;
    
    public void readData(){
        try {
            model = (DefaultTableModel) encryptedTable.getModel();
            model.setRowCount(0);
            dataMap = CommonUtils.readData();
            for (DencFile file : dataMap.values()) {
                String originalFileName = file.getOriginalFileName();
                String fileSize = df.format(CommonUtils.getFileSize(Long.parseLong(file.getFileSize())))  + " Mb";
                String encryptedFileName = file.getTempFileName();
                System.out.println(file.getPassword());
                model.addRow(new String [] { originalFileName, fileSize, encryptedFileName });
            }
            encryptedTable.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();
        encryptionScrollPane = new javax.swing.JScrollPane();
        encryptedTable = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DEncryption");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnEncrypt.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnEncrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/icons/encrypt-normal.png"))); // NOI18N
        btnEncrypt.setText("Encrypt");
        btnEncrypt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/icons/encrypt-press.png"))); // NOI18N
        btnEncrypt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/icons/encrypt-hover.png"))); // NOI18N
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnDecrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/icons/decrypt-normal.png"))); // NOI18N
        btnDecrypt.setText("Decrypt");
        btnDecrypt.setEnabled(false);
        btnDecrypt.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/icons/decrypt-press.png"))); // NOI18N
        btnDecrypt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/icons/decrypt-hover.png"))); // NOI18N
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        encryptedTable.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        encryptedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><font face=\"Courier New\" color=\"green\" size=\"6\">File Name</font></html>", "<html><font face=\"Courier New\" color=\"green\" size=\"6\">File Size</font></html>", "<html><font face=\"Courier New\" color=\"green\" size=\"6\">Encrypted File</font></html>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        encryptedTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        encryptedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encryptedTableMouseClicked(evt);
            }
        });
        encryptionScrollPane.setViewportView(encryptedTable);

        btnEdit.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encryptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDecrypt, btnEdit, btnEncrypt});

        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncrypt)
                    .addComponent(btnDecrypt)
                    .addComponent(btnEdit))
                .addGap(10, 10, 10)
                .addComponent(encryptionScrollPane)
                .addGap(10, 10, 10))
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDecrypt, btnEdit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        EncryptDialog ed = new EncryptDialog(this,this, true);
        ed.setLocationRelativeTo(this);
        ed.setVisible(true);
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int closingOption = JOptionPane.showConfirmDialog(this, "Sure to close app?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (closingOption == ConfirmationCallback.YES) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void encryptedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encryptedTableMouseClicked
        btnDecrypt.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_encryptedTableMouseClicked

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        int row = encryptedTable.getSelectedRow();
        String encryptedFileName = encryptedTable.getValueAt(row, 2).toString();
        DecryptDialog dd = new DecryptDialog(this, this, true, encryptedFileName);
        dd.setLocationRelativeTo(this);
        dd.setVisible(true);
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = encryptedTable.getSelectedRow();
        String encryptedFileName = encryptedTable.getValueAt(row, 2).toString();
        EditDialog ed = new EditDialog(this, this, true, encryptedFileName);
        ed.setLocationRelativeTo(this);
        ed.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDecrypt;
    public javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JTable encryptedTable;
    private javax.swing.JScrollPane encryptionScrollPane;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
